title: Technical Documentation
description: Installation Guide and Technical Materials
theme: jekyll-theme-minimal
markdown: kramdown

# 기본 레이아웃 설정
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "docs"
    values:
      layout: default

# URL 설정
baseurl: ""
url: "https://unknownerrrr.github.io"

# 사이트 구조 설정
collections:
  docs:
    output: true
    permalink: /:collection/:path/